### ISSUE TITLE
Calibration data understanding. 

### ISSUE THREAD

**Issue by skrealworld** [Kinect/RoomAliveToolkit#13]
Hello there, 
thanks for such helpful toolkit.
I got the calibration and now we have that calibration file. I am trying to understand the calibration data. I just want to confirm that I got it understand correctly. 
So you first you have camera pose matrix which is 4x4, this signifies the camera and universal co-ordinates system. Later color camera matrix(3x3-intrinsic) same with the depth color camera(3x3-intrinsic). And same with projector data(I am using only one pair of camera and projector). At the end there is projector pose matrix(4x4) which is co-ordinate system of projector. 
I want to map one image from camera view into projector view. So " transform pose from camera to projector and then use projector intrinsic to map 3D world of projector into 2D image" is right way to implement it?  
I apologize if I am asking inappropriate question. 
Thanks and Best Regards

**Comment by grandchild** [comment]
Yes that's exactly how it works.
The matrices are easily identifiable too. While the Camera pose is an identity, the projector pose matrix is filled and the projector intrinsics matrix is an upper triangular matrix with the 1,2-entry at 0.

**Comment by skrealworld** [comment]
Thanks grandchild for the quick reply
Suppose I want to map one image from Kinect camera view to projector view. In that case how to map the coordinate system of camera into the coordinate system of projector?
One more quick question: In the calibration file you have projector pose matrix, is that extrinsic matrix for projector with respect to camera(because camera is 1,1,1)?

**Comment by thundercarrot** [comment]
All projector poses are relative to the first depth camera.

Regarding mapping, can you be very specific about you are trying to do? Do you want to map from the depth camera or the color camera? Do you have a 2D point (image coordinates) or a 3D point (in the depth or color camera coordinate frame)?

**Comment by skrealworld** [comment]
I am trying to map 3D point(from the view of Kinect) to 3D point(from the view of projector).

**Comment by thundercarrot** [comment]
I assume you mean a 3D point in the depth camera coordinate frame? This is a simple coordinate transform, i.e. 3D point x' in projector coords is A * x, where A is the projector's 4x4 pose matrix and x is the (homogenous) point in the depth camera. x' can then be projected to projector image coordinates using the intrinsics (look for the 'Project' function in the code).

**Comment by skrealworld** [comment]
Super awesome. thanks a ton Andy. That's the thing I wanted to confirm. 
Thanks a lot again.
