### ISSUE TITLE
.OBJ file import problem

### ISSUE THREAD

**Issue by Dallemanden** [Kinect/RoomAliveToolkit#23]
Hello, when saving the scene in the calibration tool to an .OBJ file, and importing it to Unity, i get the following error:

"ImportFBX Errors:
Couldn't import file C:/Users/Admin/Desktop//Unity Projects/Test/Assets/3dobejct/3newpos2.obj.

UnityEditor.DockArea:OnGUI()"

I have done this before in an older update of the toolkit with out any problems, but now it won't load the object properly.

Any suggestions on why that might be?

The model is build from 3 proj and 3 kinects.

Thanks :+1:

**Comment by thundercarrot** [comment]
Does MeshLab load it?

**Comment by Dallemanden** [comment]
Yes it does, but it is just shown as a lot of squares.

<img width="619" alt="screen shot 2015-11-22 at 20 56 20" src="https://cloud.githubusercontent.com/assets/15942394/11325952/d26ae658-915b-11e5-8874-09ff061d1432.png">

It looks proper when i import it to Blender, however if i export it again, Unity crashes when trying to load the file.

**Comment by thundercarrot** [comment]
I can't seem to repro the problem. Can you post the file(s) somewhere where I can download it?

Are you by any chance in some locale that uses commas for decimal points? I've seen some problems with that; thought I had that licked but perhaps I missed something.

**Comment by Dallemanden** [comment]
Here is a link for the files:
https://www.dropbox.com/sh/t1riawoq9q106zo/AACH0LaNH3PvYOzUkfT6VEFka?dl=0

We are located in denmark, and yes we use commas for decimal points, but the unity installation is using dots instead of commas.

**Comment by thundercarrot** [comment]
The uploaded .obj file does indeed have commas in it where it should have points. I thought I fixed this problem using .Net's InvariantCulture (see line 1426 of ProjectorCameraEnsemble.cs). Can you verify that you are all up to date on the master branch?

**Comment by Dallemanden** [comment]
I see that aswell, hmm. The InvarianCulture should take care of the problem as you say. The calibration has been done with a fresh download from 6 days ago, so it should be all up to date.

**Comment by thundercarrot** [comment]
I changed the way InvariantCulture was being used in the export functions. I think the problem was that Vertex.ToString was carrying on without InvariantCulture. Can you try this again and let me know how it goes?

**Comment by Dallemanden** [comment]
Thank you very much. Now it works, however there are still some minor errors (according to unity)

![error](https://cloud.githubusercontent.com/assets/15942394/11372345/2d7ce182-92cd-11e5-99a7-7981dd360044.png)

But it loads fine, and does aswell in meshlab :+1:

**Comment by thundercarrot** [comment]
We could certainly add normals to the .obj file, but I'm not sure how useful this is given that the geometry is already 'lit' by the color image texture.

The vertex limit is a well known limitation in Unity. It amazes me that it exists still.

**Comment by Dallemanden** [comment]
You are right about that, and yes there is some old odd limitations in unity, just look at how they are still using quicktime in regards to handling video.
