### ISSUE TITLE
Main display and projector resolutions

### ISSUE THREAD

**Issue by nastasache** [Kinect/RoomAliveToolkit#29]
Hi Andy, 

Thank you for your great job!

Looks the main display resolution must be the same as projector resolution in order to have a good result.
I have a system with 5 monitors:
- two 3840x2160 (both 150% dpi scale)
- two 1920x1080 (both 100% dpi scale)
- one 1024x768  (100% dpi scale)

And 2 projectors:

- 1024x768
- 1920x1080

The calibrations looks working well in almost any combinations, but re-projected images are matching the captured area for me only if I set:

- 1024x768 monitor as Main Display for 1024x768 projector as extended desktop
- a 1920x1080 monitor as Main Display for 1920x1080 projector as extended desktop

Maybe is not really an issue, I am not yet well experienced with RoomAlive. I just had some headaches with finding that.

Thanks and regards,
Iulian

**Comment by thundercarrot** [comment]
Alas, RoomAlive Toolkit doesn't know about dpi-scaling, and when it is enabled it creates many problems for calibration. Try turning it off everywhere and see how that works.

I'd like to fix this, but every time I sit down to look into this, I'm astounded at how complex it is to get it right.

**Comment by nastasache** [comment]
Thanks, Andy

You are right. With dpi-scaling to 100% on all the monitors, it works with any main display.

Happy New Year!
Iulian
