### ISSUE TITLE
Surface labelling

### ISSUE THREAD

**Issue by DoNck** [Kinect/RoomAliveToolkit#32]
Hello @thundercarrot ,

First, let me thanks you for publishing your code !
I read from your RoomAlive paper about "Automatic Scene Analysis" (Hough transform, labelling) and touch detection, but I could'nt find a clue about it within the current master and develop branches. Am I right to think it will be relased later as a part of the unity plugin or did I miss it ?

Regards

**Comment by thundercarrot** [comment]
You are right; it is not in the released code. It might be some day, but I couldn't tell you when.
