### ISSUE TITLE
360 vs Xbox1

### ISSUE THREAD

**Issue by Vahid1164** [Kinect/RoomAliveToolkit#34]
Hi everyone:

I have tried to use a Kinect 360 to no avail; however, I could get the Kit to work with an Xbox One sensor. 

Is there any extra thing I should do to get Kinect 360 to work?

Thanks

**Comment by thundercarrot** [comment]
Sorry, the Toolkit doesn't support the older sensor. To do so would require a fair bit of work, beginning with a substantial rework of KinectServer.
