### ISSUE TITLE
Missing file error when buildinging the CalibrateEnsemble project

### ISSUE THREAD

**Issue by Baalumos** [Kinect/RoomAliveToolkit#35]
Hello,

I am trying to build the CalibrateEnsemble and projectionMappingSample projects and am getting the following errors:

Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\DepthAndColorGS.cso" because it was not found.	CalibrateEnsemble	
		
Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\DepthAndColorPS.cso" because it was not found.	CalibrateEnsemble	
		
Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\DepthAndColorVS.cso" because it was not found.	CalibrateEnsemble	
		
Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\BilateralFilterPS.cso" because it was not found.	ProjectionMappingSample
			
Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\DepthAndColorFloatVS.cso" because it was not found.	ProjectionMappingSample
			
Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\DepthAndColorGS.cso" because it was not found.	ProjectionMappingSample
			
Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\DepthAndColorPS.cso" because it was not found.	ProjectionMappingSample
			
Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\DepthAndColorVS.cso" because it was not found.	ProjectionMappingSample
			
Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\DepthAndProjectiveTextureVS.cso" because it was not found.	ProjectionMappingSample
			
Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\FromUIntPS.cso" because it was not found.	ProjectionMappingSample
			
Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\FullScreenQuadVS.cso" because it was not found.	ProjectionMappingSample
			
Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\MeshPS.cso" because it was not found.	ProjectionMappingSample
			
Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\MeshVS.cso" because it was not found.	ProjectionMappingSample	
		
Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\MeshWithTexturePS.cso" because it was not found.	ProjectionMappingSample	
		
Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\PassThroughPS.cso" because it was not found.	ProjectionMappingSample	
		
Could not copy the file "C:\Users\Hal\Downloads\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\RadialWobblePS.cso" because it was not found.	ProjectionMappingSample			

Can I just get a copy of these missing files and add them in? or am I missing something more fundamental?

**Comment by moonsh** [comment]
In my case, there is no error during building. 
I use Visual studio2013 and Kinect SDK 2.0

**Comment by rolandsmeenk** [comment]
You will have to build the shaders project before building the other projects. On my machine the shaders only compile when the platform is set to x64.

**Comment by Baalumos** [comment]
Thanks Roland, That was the trick!
