### ISSUE TITLE
Problem. Stripes are projeced to desktop monitor not projector

### ISSUE THREAD

**Issue by moonsh** [Kinect/RoomAliveToolkit#36]
Hello. 

Firstly, thanks for sharing this nice toolkit.
During calibration, I have faced a problem.

Visual studio2013, Kinect SDK 2.0 are used

I use one main display and the projector attached to the Pc.
I checked main display being 0 and projector display being 1 .
However, whenever I click 'Acquire', stripes are always shown in main display..
And then calibration is fail again and again.

Many thanks.

**Comment by rolandsmeenk** [comment]
Did you manually modify the calibration xml file to tell that the projector is on display index 1?

The ProjectorCameraEnsemble.Projector should contain this line:
<displayIndex>1</displayIndex>

Make sure to reload it after editing.

**Comment by moonsh** [comment]
Thanks a lot
