### ISSUE TITLE
Calibration displays on monitor not projector

### ISSUE THREAD

**Issue by racer86** [Kinect/RoomAliveToolkit#39]
When I  try and run a calibration, the stripes display on the monitor, not the projector. I have been able to properly run a calibration from a different computer that runs Windows 8, but not with this computer that runs Windows 10. When I hit the Setup, then Show Projector Server Connected Displays, the projector is labeled localhost0 and the monitor is labeled localhost1. I have changed the displayIndex to 1 but that does not fix the issue.

**Comment by devevderyadav** [comment]
hi .
 make sure that windows  display setting is extended, we also faced the same issue, resolved it by extending the display from display setting.

**Comment by racer86** [comment]
The Windows display setting is extended. I have tried switching the display settings but that does not address the problem.

**Comment by thundercarrot** [comment]
If Show Projector Server Connected Displays shows localhost0 on the projector, shouldn't you set the displayIndex to 0?

**Comment by racer86** [comment]
It turned out that we needed to download updated drivers for the computer after downloading Windows 10.

**Comment by racer86** [comment]
We were able to correctly run a calibration once. However, we are now experiencing the same issue again.

Thank you for the advice. We have tried changing the display index from 0 to 1 and back to 0, but that does not help. When we hit the Show Projector name button, the name shows up on the monitor, not the projector.

**Comment by thundercarrot** [comment]
Can you write a little C# program that does the following and see if it makes sense?

foreach (var screen in System.Windows.Forms.Screen.AllScreens) 
Console.WriteLine(screen.DeviceName + "\t" + screen.Bounds);

**Comment by racer86** [comment]
We were able to get the calibration and ProjectionMappingSample to work today. We left the displayIndex at 0.

Thank you for all of your help.
