### ISSUE TITLE
Calibration data within Opengl

### ISSUE THREAD

**Issue by tejaswidp** [Kinect/RoomAliveToolkit#52]
Can I plug in the pose of the projector into the OpenGL modelview matrix as-is without any modifications? If not, what modifications would be required?

**Comment by thundercarrot** [comment]
You might need to transpose the matrix to match the conventions of your shader (i.e., premultiply or postmultiply). It's not really so much a standard of OpenGL but rather what the shader expects.

**Comment by tejaswidp** [comment]
What about the z axis, Would I have to do something to account for the difference between directx and opengl coordinate systems.

**Comment by tejaswidp** [comment]
Closing this issue. To convert between the coordinate systems, scaling the z-axis by -1 seems to do the trick.
