### ISSUE TITLE
Can't find Shader.exe?

### ISSUE THREAD

**Issue by CedYF** [Kinect/RoomAliveToolkit#9]
I'm trying to run the program but it keeps telling that it can't find shader.exe. Am I missing something here?
![fdsfsdfsture](https://cloud.githubusercontent.com/assets/7646448/8071497/9d435dd0-0ed8-11e5-99fc-692031fa19b5.PNG)

**Comment by thundercarrot** [comment]
When you load up a solution in VS, you need to specify which project is the startup project. This is a per-user configuration, so it is not checked in, you must set it yourself by right-clicking the project and selecting Set as Startup. The Shaders project is only there to compile shader code (hlsl) and does not generate an .exe.

**Comment by CedYF** [comment]
Thanks for the response. What exactly am I suppose to set up as startup in order to run the projection mapping samples?

**Comment by thundercarrot** [comment]
Sorry to be so slow to reply; you can set ProjectionMappingSample as the startup project.
